import streamlit as st
import requests
import json
import pandas as pd
import os
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
DOCS_DIR = SCRIPT_DIR / "docs"

# Set page config
st.set_page_config(page_title="Sentiment Analysis Dashboard", page_icon="🤖", layout="wide")

st.title("Sentiment Analysis Deployment Dashboard 🚀")
st.subheader("Optimized Naive Bayes Model (Task 4)")

# Create tabs for Live API and Model Evaluation
tab1, tab2, tab3 = st.tabs(["🔴 Live API Prediction", "📈 Model Benchmarks", "🔎 Error Analysis"])

with tab1:
    st.markdown("""
    This tab interacts directly with the underlying **Flask API**.
    - The frontend receives the text.
    - The text is passed to the Flask backend via `POST /predict`.
    - Returns the required JSON structure `{"sentiment": "positive", "confidence": 0.94}`.
    """)

    # Flask API Endpoint
    API_URL = "http://127.0.0.1:5000/predict"

    # Default text from your problem description
    user_input = st.text_area("Enter your review or text here:", "This debate was completely disjointed.")

    if st.button("Predict Sentiment"):
        if not user_input.strip():
            st.warning("Please enter some text to predict.")
        else:
            with st.spinner("Calling API..."):
                try:
                    payload = {"text": user_input}
                    response = requests.post(API_URL, json=payload)
                    
                    if response.status_code == 200:
                        data = response.json()
                        sentiment = data.get("sentiment", "unknown").upper()
                        confidence = data.get("confidence", 0.0)
                        cleaned_text = data.get("cleaned_text_used", "")
                        
                        if sentiment == "POSITIVE":
                            st.success(f"**Predicted Sentiment:** {sentiment} (Confidence: {confidence}) 🟢")
                        elif sentiment == "NEGATIVE":
                            st.error(f"**Predicted Sentiment:** {sentiment} (Confidence: {confidence}) 🔴")
                        else:
                            st.info(f"**Predicted Sentiment:** {sentiment} (Confidence: {confidence}) ⚪")
                        
                        st.write(f"**Processed tokens sent to model:** `{cleaned_text}`")
                        st.markdown("### Raw API JSON Output:")
                        st.json(data)
                    else:
                        st.error(f"API returned an error ({response.status_code}): {response.text}")
                        
                except requests.exceptions.ConnectionError:
                    st.error("**Connection Error:** Cannot reach the Flask API. Make sure you run `python api.py` in a separate terminal first!")

with tab2:
    st.header("🏆 Model Benchmarks & Leaderboard")
    st.markdown("Below is the automated hyperparameter tuning leaderboard dynamically generated by `GridSearchCV` crossing 3 Text-Preprocessing Schemes with 3 specific algorithms.")
    
    leaderboard_path = DOCS_DIR / "leaderboard.csv"
    if leaderboard_path.exists():
        df_bench = pd.read_csv(leaderboard_path)
        # Highlight maximum accuracy
        st.dataframe(df_bench.style.highlight_max(subset=['Accuracy'], color='lightgreen'), use_container_width=True)
        
        best_model = df_bench.iloc[0]
        st.success(f"**Winning Model Selected for Deployment:** {best_model['Model']} using {best_model['Scheme']} at **{best_model['Accuracy']*100:.2f}% Test Accuracy**")
    else:
        st.warning("Leaderboard data missing. Run `python best_model_selection.py` first.")

with tab3:
    st.header("🔎 Evaluation & Error Analysis")
    st.markdown("Evaluating the tuned best model against the 20% holdout test chunk via the visual Confusion Matrix and isolated Error Log.")
    
    col1, col2 = st.columns([1, 1])
    
    with col1:
        st.markdown("### Visual Confusion Matrix")
        matrix_path = DOCS_DIR / "confusion_matrix.png"
        if matrix_path.exists():
            st.image(str(matrix_path), caption="Heatmap showing True vs Predicted labels")
        else:
            st.warning("Confusion matrix missing. Run `python error_analysis.py`.")
            
    with col2:
        st.markdown("### Raw Misclassifications Logs")
        errors_path = DOCS_DIR / "model_errors.csv"
        if errors_path.exists():
            df_errors = pd.read_csv(errors_path)
            st.metric(label="Total Misclassifications in Test Set", value=len(df_errors))
            st.dataframe(df_errors, use_container_width=True)
        else:
            st.warning("Error data missing. Run `python error_analysis.py`.")
